services:
  #db:
  #  build:
  #    context: .
  #    dockerfile: dockerfiles/postgres/Dockerfile
  #  image: dss-postgres
  #  container_name: dss-postgres
  #  ports:
  #    - "5432:5432"
  #  environment:
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=postgres12345
  #    - PGPASSWORD=postgres12345
  #    - POSTGRES_DB=dsdojo_db
  #    - DATABASE_HOST=localhost
  #  volumes:
  #    - ./docker/db/init:/docker-entrypoint-initdb.d
  #    - ./docker/work/data:/tmp/data

  notebook:
    build:
      context: .
      dockerfile: dockerfiles/notebook/Dockerfile
    image: my-jupyter
    platform: linux/arm64
    container_name: my-jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - BASE_URL=${BASE_URL}
      - BYPASS_API_BASE_URL=${BYPASS_API_BASE_URL}
      - MCR_ROAD_TYPE_API_KEY=${MCR_ROAD_TYPE_API_KEY}
      # for GDAL
      - GDAL_VERSION=3.7.3
      - GDAL_CONFIG=/usr/local/bin/gdal-config
      - CPLUS_INCLUDE_PATH=/usr/include/gdal
      - C_INCLUDE_PATH=/usr/include/gdal
      - LIBRARY_PATH=/usr/lib
    volumes:
      - ./docker/work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
