version: "3.8"

services:
  #db:
  #  build:
  #    context: .
  #    dockerfile: dockerfiles/postgres/Dockerfile
  #  image: dss-postgres
  #  container_name: dss-postgres
  #  ports:
  #    - "5432:5432"
  #  environment:
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=postgres12345
  #    - PGPASSWORD=postgres12345
  #    - POSTGRES_DB=dsdojo_db
  #    - DATABASE_HOST=localhost
  #  volumes:
  #    - ./docker/db/init:/docker-entrypoint-initdb.d
  #    - ./docker/work/data:/tmp/data

  notebook:
    build:
      context: .
      dockerfile: dockerfiles/notebook/Dockerfile
    image: pyopt-notebook
    container_name: pyopt-notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - MCR_ROAD_TYPE_API_KEY=${MCR_ROAD_TYPE_API_KEY}
    volumes:
      - ./docker/work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''

  app:
    build:
      context: .
      dockerfile: dockerfiles/flask/Dockerfile
    ports:
      - "4000:5000"
    container_name: app
    volumes:
      - ./docker/work/submodules/PyOptBook/6.api:/usr/src/app
    command: flask run --host=0.0.0.0
