services:
  jupyter:
    build:
      context: .
      dockerfile: dockerfiles/notebook/Dockerfile
    image: my-jupyter:latest  # この行を追加
    deploy:
      resources:
        limits:
          memory: 15g
    ports:
      - "8888:8888"
    volumes:
      - ./docker/work:/app/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
